### ISSUE TITLE
Dockerfile error message

### ISSUE THREAD

**Issue by mayanicole** [Identity-Framework/BioNode-Client#8]
invalid value "Dockerfile" for flag -t: Error parsing reference: "Dockerfile" is not a valid repository/tag

**Comment by corysabol** [comment]
Will look into this today, while I structure the project some more.

**Comment by corysabol** [comment]
I may have made a mistake in the build instructions.
The updated instructions are reflected [here](https://github.com/Identity-Framework/BioNode/wiki/Development-and-Testing) on the wiki.

Please try and execute `docker build -t <imagename> .` where `<imagename>` is a name of your choice for the consequently generated docker image.

Let me know the results of trying that.

**Comment by corysabol** [comment]
Closing as no longer relevant.
